name: bl4ckkitCore
main: bl4ckscor3.plugin.bl4ckkitCore.core.bl4ckkitCore
version: 1.1
author: bl4ckscor3
description: Provides core functionality for my other plugins 
commands:
    bl4ckkitcore:
        description: Lists all registered plugins (aka plugins which use bl4ckkitCore)
        usage: /<command>
        aliases: [bl4ck,bl4Core,core]
permissions:
    bl4Core.bl4ckkitcore:
        description: Gives access to the /bl4ckkitcore command.
        default: op